import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Hero, ColorSection, Navbar, ThemePallete, Footer } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Hero />
        <ColorSection />
        {children}
        <section>
          <ThemePallete />
        </section>
          <Footer />
      </body>
    </html>
  );
}
